# Generated by Django 4.1.2 on 2022-10-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', '負責主要照顧責任'), ('2', '協助家人顧顧與蒐集資訊'), ('3', '從事照顧相關工作的人'), ('4', '對照護議題感興趣')], default='1', max_length=20, verbose_name='目前您的照顧角色'),
        ),
    ]
