# Generated by Django 4.1.2 on 2022-10-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_role_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='這位家人的生日'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='care_time',
            field=models.CharField(choices=[('1', '即將開始照顧'), ('2', '開始半年內'), ('3', '半年~1年'), ('4', '1年~3年'), ('5', '3年~5年'), ('6', '5年以上')], default=2, max_length=20, verbose_name='已照顧多久時間'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cared_person',
            field=models.CharField(blank=True, max_length=20, verbose_name='我們如何稱呼這位家人'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q1',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='照顧壓力大的時候，我希望可以自己靜一靜'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q10',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='照顧家人的時候，可以出錢也可以出力，但照顧責任應該要公平'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='參與團體活動，能夠放鬆我的照顧壓力'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='有聽說新的照顧用品對照顧對象有幫助，我會馬上嘗試'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q4',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='當購買新的照顧器材時，我會一步一步按照說明進行做操作'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q5',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='在進行照顧決策時，我會認為對於被照顧者有幫助，比起家人們的意願更重要'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q6',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='聽到照顧對象講的話不合邏輯時，我會理解他而不是說服他'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q7',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='照顧家人的時候，我會希望將所有會用到的資訊記錄下來'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q8',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='日常照顧充滿混亂，但我會盡力讓過程井井有條'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q9',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, verbose_name='分工照顧家人的時候，有能力的人應該要勇於承擔'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', '負責主要照顧責任'), ('2', '協助家人顧顧與蒐集資訊'), ('3', '從事照顧相關工作的人'), ('4', '對照護議題感興趣')], default='1', max_length=20, verbose_name='目前您的照顧角色'),
        ),
    ]
