# Generated by Django 4.1.2 on 2022-10-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_userprofile_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhabitants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(verbose_name='生於民國幾年')),
                ('inhabit_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitant_person', to='app.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
