# Generated by Django 4.1.2 on 2022-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inhabitants'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='city',
            field=models.CharField(choices=[('0', '新北市'), ('1', '台北市'), ('2', '桃園市'), ('3', '台中市'), ('4', '台南市'), ('5', '高雄市'), ('6', '宜蘭市'), ('7', '新竹縣'), ('8', '苗栗縣'), ('9', '彰化縣'), ('10', '南投縣'), ('11', '雲林縣'), ('12', '嘉義縣'), ('13', '嘉義市'), ('14', '屏東縣'), ('15', '台東縣'), ('16', '花蓮縣'), ('17', '澎湖縣'), ('18', '基隆市'), ('19', '新竹市'), ('20', '金門縣'), ('21', '連江縣')], max_length=3, null=True, verbose_name='居住縣市'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='resident',
            field=models.CharField(max_length=10, null=True, verbose_name='居住地'),
        ),
    ]
