# Generated by Django 4.1.2 on 2022-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inhabitants_city_inhabitants_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
