# Generated by Django 4.1.2 on 2022-10-31 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_inhabitants_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
