# Generated by Django 4.1.2 on 2022-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_inhabitants_inhabit_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='difficulty_care',
            field=models.CharField(choices=[(0, '盥洗困難'), (1, '淋浴困難'), (2, '排尿排便困難'), (3, '如廁困難'), (4, '更衣困難'), (5, '進食困難'), (6, '移位困難'), (7, '步行困難'), (8, '上下樓困難')], max_length=255, null=True, verbose_name='自理困難處'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='mobility',
            field=models.CharField(choices=[(0, '行動自如'), (1, '不平坦地面行走吃力'), (2, '需攙扶或拿拐杖行走'), (3, '無法行走，可維持坐姿'), (4, '無法維持坐姿')], max_length=255, null=True, verbose_name='行動能力'),
        ),
    ]
