# Generated by Django 4.1.2 on 2022-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inhabitants_difficulty_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='budget',
            field=models.CharField(max_length=255, null=True, verbose_name='預估家庭能負擔的照顧費'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='cohabitant',
            field=models.CharField(max_length=255, null=True, verbose_name='跟誰一起住'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='exception',
            field=models.CharField(max_length=255, null=True, verbose_name='家庭期待的照顧方式'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='life_difficulty',
            field=models.CharField(max_length=255, null=True, verbose_name='生活困難處'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='resource',
            field=models.CharField(max_length=255, null=True, verbose_name='使用外部資源'),
        ),
    ]
