# Generated by Django 4.1.2 on 2022-10-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_inhabitants_budget_inhabitants_cohabitant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhabitants',
            name='inhabit_person',
        ),
    ]
