# Generated by Django 4.1.2 on 2022-11-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_inhabitants_inhabit_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitants',
            name='mobility',
            field=models.CharField(max_length=255, null=True, verbose_name='行動能力'),
        ),
    ]
