# Generated by Django 4.1.2 on 2022-11-01 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersurvey', to=settings.AUTH_USER_MODEL),
        ),
    ]
