# Generated by Django 4.1.2 on 2022-11-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q11',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='親人是否有儲蓄能夠支付自己的照顧相關費用？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q12',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='親人是否願意將個人儲蓄用在自己的照顧相關費用上？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q13',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否能估計親人的醫療與照顧相關費用，所衍伸的花費金額？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q14',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你清楚可選擇的照顧選項之中，政府所提供的各項補助金額與申請條件？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q15',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否有評估過自己理想老後照顧方式所需之費用，並提前進行規劃與儲蓄？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q16',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你認為長輩於生活中口頭承諾遺產分配，是否能夠產生法律效益呢？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q17',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否知道，主要照顧者能藉由設定契約、信託、意定監護等方式，保障勞力與金錢長期付出對應之權益嗎？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q18',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否知道，若要避免維生醫療與侵入性治療（氣切、CPR...等），需提前申請並依規定簽署相關證明文件嗎？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q19',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你認為你的親友之間，是否會因為照顧責任或財產問題告上法庭？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q20',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否考慮過，讓長輩提前進行遺產規劃並預立遺囑來減少家中的紛爭？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q21',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='日常照顧過程中，你是否擁有一段自己獨處的時間\\空間，放鬆與轉換心情？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q22',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='在家中，是否有其他家人能夠共同討論照顧上的壓力？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q23',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='是否會因為照顧的親人的身心狀況嚴重產生不捨或者同情，影響到照顧的情緒'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q24',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你是否會因為照顧時間太長，時長感到憤怒、疲憊與壓力大？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q25',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你面對照顧負面情緒時，你是否有管道能夠抒發壓力？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q26',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你的家人們，能夠針對照顧與醫療方式達成共識?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q27',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='在家中，是否有其他家人能夠共同討論照顧上的壓力？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q28',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='親人是否有儲蓄能夠支付自己的照顧相關費用？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q29',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='是否有和其他家人同步每日照顧狀況（例如：看診紀錄、突發狀況、身體量測數字等等）的習慣？'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q30',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你能夠與其他家人開啟照顧費用相關的討論 ，並取得共識？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q1',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='看診時，你或家人能夠理解並實際執行醫生之指示'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q10',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你或家人能夠執行每日親人的身體照顧需求（例如：肢體運動、翻身拍背、如廁、盥洗……等）？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你或家人有足夠的儲蓄面對照顧狀況'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你或家人總是能夠陪伴照顧對象去門診'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q4',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你或家人能夠搜尋附近的醫療資源'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q5',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你知道此病症未來可能發生的變化'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q6',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你知道外籍看護、台籍看護、銀髮住宅、機構、日照或護理之家等照顧選項的優缺點？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q7',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你知道照顧過程與親人病症，可能遇到的潛在風險？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q8',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='當你需要協助時，可以找到其他人協助照顧？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q9',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], max_length=10, null=True, verbose_name='你或家人能夠協助照顧親人的日常起居（例如：三餐、穿衣、社交、外出......等）？'),
        ),
    ]
