# Generated by Django 4.1.2 on 2022-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_survey_q1_alter_survey_q10_alter_survey_q11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='q10',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q11',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q12',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q13',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q14',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q15',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q16',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q17',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q18',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q19',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q20',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q21',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q22',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q23',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q24',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q25',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q26',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q27',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q28',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q29',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q30',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q4',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q5',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q6',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q7',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q8',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q9',
            field=models.CharField(choices=[('5', '非常同意'), ('4', '同意'), ('3', '沒有意見'), ('2', '不同意'), ('1', '非常不同意')], default='0', max_length=10, null=True),
        ),
    ]
